### ISSUE TITLE
Summary of findings from interviews

### ISSUE THREAD

**Issue by kristenfrederick** [ESIPFed/soil_data_model_survey#2]
I added in a results section for the interview portion that summarizes the general findings of each question. This was based on the results document that we have been working on. See 3329c16 Can @ktoddbrown review this commit?

**Comment by ktoddbrown** [comment]
Rewrote things a little here: 4428850e54642fb5e502add5c3d636fcb55a74c1 see what you think.

**Comment by kristenfrederick** [comment]
Looks good! @ktoddbrown

**Comment by ktoddbrown** [comment]
Done df39b28
